const ACTION_TYPES = {
  TOGGLE_POSTS_LOADING: 'TOGGLE_POSTS_LOADING',
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RESET_POSTS: 'RESET_POSTS',
  REFRESH_POSTS: 'REFRESH_POSTS',
};

export default ACTION_TYPES;
